### ISSUE TITLE
Change upload size limit from Byte to MB

### ISSUE THREAD

**Issue by jwillmer** [StarcounterPrefabs/Images#41]
Have you tried to set a 10MB file size limit?

If I use Google for the calculation I get:
![calc](https://cloud.githubusercontent.com/assets/1503577/18470463/4fb538f6-79b5-11e6-9cd0-a445c6dc3cd0.png)

Have fun adding this ;)

**Comment by warpech** [comment]
Fixed in #46, waits for merging.

**Comment by warpech** [comment]
Fixed in `SweOffshore-Checklist-UriMapping` branch. Thanks for the contribution!
