### ISSUE TITLE
Replace the "+ Image" icon

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Images#48]
### Steps to reproduce

1. Go to the "Images" app partial that show the image carousel
2. Check how the "Image" icon looks like

### Expected result

The icon should look like designed in https://github.com/Starcounter/EpicDemo/blob/master/Screenshots/Individual.png

![screen shot 2016-09-22 at 14 07 47](https://cloud.githubusercontent.com/assets/566463/18747499/ff1b1a08-80cd-11e6-9c54-1fdda76d00dc.png)

### Actual result

The icon looks differently:

![2016-09-22 14_05_51-launcher](https://cloud.githubusercontent.com/assets/566463/18747438/b6ce50e4-80cd-11e6-9906-6160a372aab5.png)

##### Involved apps' version

StarcounterPrefabs/Launcher@5.0.0-develop.1
Images https://github.com/StarcounterPrefabs/Images/commit/d3ffcf1322114e407e13436540d698f0567fc408
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge (did not check)
- [ ] Safari 9 (did not check)
- [ ] Safari 8 (did not check)
- [ ] IE 11 (did not check)

**Comment by diliger** [comment]
done.

But button is wider to match the width of thumbnails 
![image](https://cloud.githubusercontent.com/assets/15857369/19289266/9dfd91de-9012-11e6-9dc8-0d42447ae623.png)
