### ISSUE TITLE
Change and document the architecture of the partials

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Images#49]
The architecture of the Images app has drifted into 2 different directions recently, and became unmergable. There is:
- `develop` branch with the new carousel view and video upload support -- all added to existing partials
- `SweOffshore-Checklist-UriMapping` branch with mobile view -- created as new partials

Because of this, the two branches became unmergable. We need to find a way to fix this.

The partials of the images app should be the following:
- `ContentPage.html` - is a readonly view of a single image or video (desktop or mobile)
- `EditableContentPage.html` - same as above but it is possible to upload and delete
- `IllustrationsPage.html` - is a carousel that allows to switch between the ContentPages
- `EditableIllustrationsPage.html` - same as above but for EditableContentPages

I propose that this should be fixed by @diliger on a feature branch, then peer reviewed and merged to `develop`.

Later, @aloscha should merge `SweOffshore-Checklist-UriMapping` to `develop`.

I would like to do all that next week. Can we have a meeting on Monday to discuss it?

cc @diliger, @aloscha

**Comment by warpech** [comment]
I totally didn't manage to do this. I would like all of the 4 mappable partials to be described as in this template: 

https://github.com/StarcounterPrefabs/Images/blob/e5ff800400725e5aeae037a5466d2f0549c223c4/README.md#get-imagespartialsconcept

If someone wants to take this over before Monday, this would be great. Otherwise, I will continue next week.

**Comment by warpech** [comment]
I have finished a sample partial documentation and merged it to `master`, because it is needed in HelloWorld. 

For the purpose of this issue, we need to define the documentation for the other partials.

**Comment by warpech** [comment]
Part of the work done by @diliger is now merged to `develop`. Now @aloscha it is your turn. Please feel free to do refactoring of things that you find odd. Please work on a separate branch and do a PR to `develop`.

**Comment by aloscha** [comment]
Thanks @warpech, yesterday I fixed my stuff, today I will push changes etc. I've also create fiew bugs and enhancements for @diliger : https://github.com/StarcounterPrefabs/Images/issues/52, https://github.com/StarcounterPrefabs/Images/issues/53, https://github.com/StarcounterPrefabs/Images/issues/54, https://github.com/StarcounterPrefabs/Images/issues/55

**Comment by warpech** [comment]
@aloscha what's the status of this?

**Comment by aloscha** [comment]
I've merge SO branch with develop and resolve conflicts locally. Now I will fix some unused partial (I think I will manage it by the end of this weekend).

**Comment by diliger** [comment]
what branch can i use now?

**Comment by aloscha** [comment]
@diliger for your changes please use `Develop` branch

**Comment by aloscha** [comment]
I've create pr for @warpech with all changed, which I made in ImagesApp. I've also fix some bugs with preview and edit: https://github.com/StarcounterPrefabs/Images/issues/53 and https://github.com/StarcounterPrefabs/Images/issues/52

Also prepare solution for new partials and remove redundant ones. Also fix with SO.

**Comment by aloscha** [comment]
It's fixed here - https://github.com/StarcounterPrefabs/Images/pull/60
