### ISSUE TITLE
Edit/Delete doesn't work on Develop

### ISSUE THREAD

**Issue by aloscha** [StarcounterPrefabs/Images#52]
After I add few images I couldn't delete anything - delete button shows dialog, but no action there (after refresh the same).

The same problem with Edit button. I clicked it and nothing happens, just address changes but page still the same. If I try to refresh page manually I have NullReferenceException

**Comment by diliger** [comment]
What page? Can you please attach a screenshot?

**Comment by diliger** [comment]
@aloscha is it fixed now?

**Comment by warpech** [comment]
@aloscha what's the status of this one? Please make sure that you inform on GitHub what's your intention. Right now there are two commits created by you despite the issue was self-assigned by @diliger.

**Comment by warpech** [comment]
@aloscha ping

**Comment by aloscha** [comment]
I fix that issue by my own and I think in pr you already check it

**Comment by aloscha** [comment]
Fixed in https://github.com/StarcounterPrefabs/Images/pull/60
