### ISSUE TITLE
Rewrite juicy-carousel to starcounter-composition

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Images#61]
It seems that `<juicy-carousel>` https://github.com/StarcounterPrefabs/Images/blob/develop/src/Images/wwwroot/Images/elements/juicy-carousel/juicy-carousel.html
has no special functionality and it's just HTML structure and set of CSS rules applied in shadow DOM.

If we want just declarative Shadow DOM. plus improve performance (get rid of CE & HTML Import overhead),  code clarity and blending. `starcounter-composition` is the way to go! :)

It seems that we can simply move entire code into composition :) 

// cc @diliger 
BTW, It's also not a juicy element ;)

**Comment by aloscha** [comment]
https://github.com/StarcounterPrefabs/Images/pull/62

@diliger up?

**Comment by diliger** [comment]
can be closed now?

**Comment by tomalec** [comment]
Please see https://github.com/StarcounterPrefabs/Images/pull/62#pullrequestreview-19066665

**Comment by warpech** [comment]
Issues cannot be closed until PRs that implement them are merged

**Comment by aloscha** [comment]
Done (https://github.com/StarcounterPrefabs/Images/pull/62)
