### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by mmnosek** [StarcounterPrefabs/Images#69]
Some files are not included into project but still exists in the repo. I think that we don't need them anymore. Some examples:
- ConceptIllustrationPage.json.cs
- PreviewPage.json

etc. Easy to discover using Visual Studio

cc @aloscha

**Comment by aloscha** [comment]
yeah agreed, should be removed

**Comment by mmnosek** [comment]
Changes in #70 Thanks a lot @aloscha!
